FROM continuumio/anaconda3

WORKDIR /app

# Create conda environment
COPY environment.yml .
# COPY requirements.txt .
# RUN pip install -r requirements.txt
RUN conda env create -f environment.yml


# Make RUN commands use the conda environment
SHELL ["conda", "run", "-n", "topobert", "/bin/bash", "-c"]

RUN python -c "import flask"

# The code to run when container is started:
COPY run.py .
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "myenv", "python", "run.py"]