name: topobert
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.4.26
  - certifi=2021.5.30
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=21.2.2
  - python=3.6.13
  - readline=8.1.2
  - sqlite=3.38.5
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - cffi==1.15.1
    - click==8.0.4
    - cmake==3.22.5
    - cycler==0.11.0
    - dataclasses==0.8
    - decorator==4.4.2
    - diskcache==5.4.0
    - flask==2.0.3
    - flask-cors==3.0.10
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - itsdangerous==2.0.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - kiwisolver==1.3.1
    - kmapper==2.0.1
    - kneed==0.7.0
    - llvmlite==0.36.0
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - networkx==2.5.1
    - numba==0.53.1
    - numpy==1.19.5
    - pandas==1.1.5
    - pillow==8.4.0
    - pycparser==2.21
    - pynndescent==0.5.7
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - setuptools==59.6.0
    - six==1.16.0
    - sklearn==0.0
    - threadpoolctl==3.1.0
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - umap-learn==0.5.3
    - werkzeug==2.0.3
    - zipp==3.6.0
