export const defaults = {
  defaultEpochs: [
    0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
    165, 170, 175, 176,
  ],
  defaultMapperParams: {
    dataSplit: {
      paramList: [
        { name: 'Train', value: 'train' },
        { name: 'Test', value: 'test' },
        { name: 'Train ∪ Test', value: 'trainutest' },
        { name: 'Train + Test (knn)', value: 'trainknntest' },
      ],
      selected: 'train',
    },
    metric: {
      paramList: [
        { name: 'Euclidean', value: 'euclidean' },
        { name: 'Cosine', value: 'cosine' },
      ],
      selected: 'euclidean',
    },
    filter: {
      paramList: [
        { name: 'L1', value: 'l1' },
        { name: 'L2', value: 'l2' },
        { name: 'Average KNN-5', value: 'knn' },
      ],
      selected: 'l1',
    },
    intervals: {
      paramList: [
        { name: '50', value: 50 },
        { name: '100', value: 100 },
      ],
      selected: 50,
    },
    overlap: {
      paramList: [
        { name: '25', value: 25 },
        { name: '50', value: 50 },
        { name: '100', value: 100 },
      ],
      selected: 50,
    },
    layout: {
      paramList: [
        { name: 'Force Directed', value: 'force' },
        { name: 'PCA', value: 'pca' },
      ],
      selected: 'force',
    },
  },
  defaultLayerObj: {
    layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    selected: 0,
  },
  defaultDatasetList: {
    datasets: [
      { name: 'SuperSense Role', value: 'ss-role' },
      { name: 'SuperSense Function', value: 'ss-func' },
      { name: 'Part of Speech', value: 'pos' },
      { name: 'Dependency', value: 'dep' },
    ],
    selected: 'ss-role',
  },
  defaultColorScheme: {
    'p.Circumstance': { color: '#00429d', selected: false },
    'p.Time': { color: '#5e5caf', selected: false },
    'p.StartTime': { color: '#5e5caf', selected: false },
    'p.EndTime': { color: '#5e5caf', selected: false },
    'p.Frequency': { color: '#8f7ac0', selected: false },
    'p.Duration': { color: '#b89bd3', selected: false },
    'p.Interval': { color: '#debfe8', selected: false },
    'p.Locus': { color: '#ffe5ff', selected: false },
    'p.Goal': { color: '#ffe5ff', selected: false },
    'p.Source': { color: '#ffe5ff', selected: false },
    'p.Path': { color: '#eabcdd', selected: false },
    'p.Direction': { color: '#d693b8', selected: false },
    'p.Extent': { color: '#d693b8', selected: false },
    'p.Means': { color: '#c26a90', selected: false },
    'p.Manner': { color: '#ad3f65', selected: false },
    'p.Explanation': { color: '#93003a', selected: false },
    'p.Purpose': { color: '#93003a', selected: false },
    'p.Causer': { color: '#486721', selected: false },
    'p.Agent': { color: '#486721', selected: false },
    'p.Co-Agent': { color: '#486721', selected: false },
    'p.Theme': { color: '#658b4f', selected: false },
    'p.Co-Theme': { color: '#658b4f', selected: false },
    'p.Topic': { color: '#658b4f', selected: false },
    'p.Stimulus': { color: '#85af7d', selected: false },
    'p.Experiencer': { color: '#a8d5ad', selected: false },
    'p.Originator': { color: '#d0fbdd', selected: false },
    'p.Recipient': { color: '#afeccc', selected: false },
    'p.Cost': { color: '#8cddbf', selected: false },
    'p.Beneficiary': { color: '#63ceb4', selected: false },
    'p.Instrument': { color: '#22bfac', selected: false },
    'p.Identity': { color: '#ecad00', selected: false },
    'p.Species': { color: '#f4b842', selected: false },
    'p.Gestalt': { color: '#fac368', selected: false },
    'p.Possessor': { color: '#fac368', selected: false },
    'p.Whole': { color: '#fac368', selected: false },
    'p.Characteristic': { color: '#ffcf8a', selected: false },
    'p.Possession': { color: '#ffcf8a', selected: false },
    'p.PartPortion': { color: '#ffcf8a', selected: false },
    'p.Stuff': { color: '#ffcf8a', selected: false },
    'p.Accompanier': { color: '#ffdbac', selected: false },
    'p.ComparisonRef': { color: '#ffe8ce', selected: false },
    'p.RateUnit': { color: '#f5c8a2', selected: false },
    'p.Quantity': { color: '#eca87c', selected: false },
    'p.Approximator': { color: '#eca87c', selected: false },
    'p.SocialRel': { color: '#d86042', selected: false },
    'p.OrgRole': { color: '#cd3030', selected: false },
    Others: { color: '#989898', selected: false },
    'p.Test': { color: '#c7c7c7', selected: false },
  },
  defaultTable: {
    header: ['sent_id', 'word_id', 'word', 'label'],
    rows: [
      // TODO: Replace with approriate interface
      ['a', 'b', 'c', 'd'],
      ['a', 'b', 'c', 'd'],
      ['a', 'b', 'c', 'd'],
    ],
  },
  defaultGraph: null,
};
